2025-10-13 19:52:04,780 INFO    MainThread:9332 [wandb_setup.py:_flush():81] Current SDK version is 0.22.2
2025-10-13 19:52:04,780 INFO    MainThread:9332 [wandb_setup.py:_flush():81] Configure stats pid to 9332
2025-10-13 19:52:04,781 INFO    MainThread:9332 [wandb_setup.py:_flush():81] Loading settings from C:\Users\Kundan Mourya\.config\wandb\settings
2025-10-13 19:52:04,781 INFO    MainThread:9332 [wandb_setup.py:_flush():81] Loading settings from D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\wandb\settings
2025-10-13 19:52:04,781 INFO    MainThread:9332 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-10-13 19:52:04,781 INFO    MainThread:9332 [wandb_init.py:setup_run_log_directory():705] Logging user logs to D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\wandb\run-20251013_195204-6pj47ica\logs\debug.log
2025-10-13 19:52:04,783 INFO    MainThread:9332 [wandb_init.py:setup_run_log_directory():706] Logging internal logs to D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\wandb\run-20251013_195204-6pj47ica\logs\debug-internal.log
2025-10-13 19:52:04,783 INFO    MainThread:9332 [wandb_init.py:init():832] calling init triggers
2025-10-13 19:52:04,784 INFO    MainThread:9332 [wandb_init.py:init():837] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-10-13 19:52:04,784 INFO    MainThread:9332 [wandb_init.py:init():880] starting backend
2025-10-13 19:52:07,072 INFO    MainThread:9332 [wandb_init.py:init():883] sending inform_init request
2025-10-13 19:52:07,146 INFO    MainThread:9332 [wandb_init.py:init():891] backend started and connected
2025-10-13 19:52:07,149 INFO    MainThread:9332 [wandb_init.py:init():961] updated telemetry
2025-10-13 19:52:07,161 INFO    MainThread:9332 [wandb_init.py:init():985] communicating run to backend with 90.0 second timeout
2025-10-13 19:52:08,875 INFO    MainThread:9332 [wandb_init.py:init():1036] starting run threads in backend
2025-10-13 19:52:09,495 INFO    MainThread:9332 [wandb_run.py:_console_start():2509] atexit reg
2025-10-13 19:52:09,496 INFO    MainThread:9332 [wandb_run.py:_redirect():2357] redirect: wrap_raw
2025-10-13 19:52:09,496 INFO    MainThread:9332 [wandb_run.py:_redirect():2426] Wrapping output streams.
2025-10-13 19:52:09,496 INFO    MainThread:9332 [wandb_run.py:_redirect():2449] Redirects installed.
2025-10-13 19:52:09,507 INFO    MainThread:9332 [wandb_init.py:init():1076] run started, returning control to user process
2025-10-13 19:52:09,521 INFO    wandb-AsyncioManager-main:9332 [service_client.py:_forward_responses():80] Reached EOF.
2025-10-13 19:52:09,521 INFO    wandb-AsyncioManager-main:9332 [mailbox.py:close():137] Closing mailbox, abandoning 2 handles.
2025-10-13 19:52:12,166 ERROR   MainThread:9332 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\.venv\Lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\.venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 2430, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\.venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\.venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\.venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 1595, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\.venv\Lib\site-packages\wandb\sdk\interface\interface.py", line 802, in publish_output_raw
    self._publish_output_raw(o)
  File "D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\.venv\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 37, in _publish_output_raw
    self._publish(rec)
  File "D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\.venv\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 43, in _publish
    self._asyncer.run(lambda: self._client.publish(request))
  File "D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\.venv\Lib\site-packages\wandb\sdk\lib\asyncio_manager.py", line 136, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\python\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\.venv\Lib\site-packages\wandb\sdk\lib\asyncio_manager.py", line 219, in _wrap
    return await fn()
           ^^^^^^^^^^
  File "D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\.venv\Lib\site-packages\wandb\sdk\lib\service\service_client.py", line 38, in publish
    await self._send_server_request(request)
  File "D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\.venv\Lib\site-packages\wandb\sdk\lib\service\service_client.py", line 64, in _send_server_request
    await self._writer.drain()
  File "C:\python\Lib\asyncio\streams.py", line 378, in drain
    await self._protocol._drain_helper()
  File "C:\python\Lib\asyncio\streams.py", line 167, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
